backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
    - label: "Featured Image"
    name: "Banner"
    widget: "image"
    choose_url: true
    default: "../assets/man-on-bike.jpg"
    media_library:
      config:
        multiple: true
